#!/bin/bash

# Variables
CONTAINER_ID=`docker ps -q --filter="name=pg_postgres.1.*"`
BACKUP_FOLDER=./backup/pg
TIMESTAMP=`date +%F-%H%M`



echo 'Variables-------'
echo 'CONTAINER_ID='${CONTAINER_ID}
echo 'BACKUP_FOLDER='${BACKUP_FOLDER}

# Clean up
echo 'Running cleanup-------'
rm -rf ${BACKUP_FOLDER}
mkdir -p ${BACKUP_FOLDER}

# Backup commands
echo 'Generating backup-------'
for db in $(docker exec -i ${CONTAINER_ID} psql -U postgres -t -c 'SELECT datname FROM pg_database WHERE NOT datistemplate')
do
  echo $db
  docker exec -i ${CONTAINER_ID} pg_dump -U postgres --format=c ${db} > ${BACKUP_FOLDER}/${db}.sqlc
 
done
tar -zcvf $TIMESTAMP.tar.gz ./backup/pg

aws s3 sync $BACKUP_FOLDER s3://drogoprod/$TIMESTAMP


rm -rf $TIMESTAMP.tar.gz 

echo 'Done-------'
